### PR TITLE
Chore: fixed issues affecting code quality

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes
- Change methods not using its bound instance to staticmethods

> this will boost minor performance

- Refactor unnecessary `else` / `elif` when `if` block has a `return` statement

> this fixed the antipattern

### CODE REVIEW

**Comment by akanz1** [comment]
Nice finds, thank you!

**Comment by withshubh** [comment]
@akanz1 

I would like to inform you that these issues were caught by [DeepSource](https://deepsource.io/) on my fork of this repository. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/klib/issues/?category=recommended).

DeepSource is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

What do you think?

**Comment by withshubh** [comment]
@akanz1 
Can I submit a new PR with the configuration file which I used to configure the analysis?
You can merge the configuration file to continuously analyze the repo and fix code quality issues.

**Comment by akanz1** [comment]
@withshubh feel free to do so. I did integrate deep source already a couple of days ago, seems like an interesting tool.

**Comment by withshubh** [comment]
> @withshubh feel free to do so. I did integrate deep source already a couple of days ago, seems like an interesting tool.

Thanks! @akanz1 :sparkling_heart: 

I don't find the need to submit the PR for the configuration file(.deepsource.toml) since you've already integrated DeepSource and the configuration is similar.

Also, I work at DeepSource. So, If you have any suggestion/advice on what we can do to improve our analyzer then you can share that with me.

**Pull request merged**
