### PR TITLE
[FEATURE] - corr_plot using plotly

### PR DESCRIPTION
**Pull request by m-marqx**
| name | about | title | labels | assignees |
| --- | --- | --- | --- | --- |
| Feature Addition | interactive version from corr_plot | [FEATURE] - corr_plot using plotly | Plot | @m-marqx | 

The purpose of this function is to allow users to explore and interact with correlation data dynamically, similar to the `corr_plot`, but using Plotly instead of Matplotlib.

The function takes the same user parameters as seen in `corr_plot(data, split, threshold, target, method, cmap, figsize, annot)`. The difference between corr_plot and corr_interactive_plot lies in **kwargs to customize the visualization using the heatmap from graph objects from Plotly. I opted for this method and not `.imshow` from plotly.express because it offers fewer options for user customization.

My original idea was to update the corr_plot with `interactive: bool = False` and place the function `corr_interactive_plot` as a private function inside `corr_plot`. However, this could make the function appear complex and challenging for users to comprehend the interactive version.

klib_plot

### CODE REVIEW

**Comment by akanz1** [comment]
@m-marqx Thank you for your contribution, this looks great! I will have a close look in the next 1-2 days and get back to you. :)

**Review by akanz1 — CHANGES_REQUESTED** [review]
Looks good except for the minor type hint updates. Once those have been addressed we cna merge this and i'll play around with it a bit before drafting a new release. Thanks again!

**Comment by akanz1** [comment]
Also, please merge in `main` as there have been some minor changes in other parts of the code (shouldn't give you any conflicts).

**Comment by m-marqx** [comment]
I'm glad you liked the contribution! 

I hope the changes will be helpful for the project. 

Let me know if there's anything else I can assist with.

**Review by akanz1 — APPROVED** [review]

**Comment by akanz1** [comment]
Linting failed but i will deal with this once i do some test runs. 

If you are interested you can add an image of the new plot to the documentation (`readme.md` and in `/examples`) similar to what is already there, probably best to add it below the corr_plot image.

**Pull request merged**
